name: Update a Pull request's description
description: Update a Pull request's description with PR related links

inputs:
  app-name:
    description: Name of the App
    required: false
  redoc-links:
    description: Redoc links for the PR
    required: false
  coverage-links:
    description: Coverage links for the PR
    required: false
  badge:  
    description: Badge from the PR
    required: false
  main-coverage:    
    description: Coverage from the main branch
    required: false
  main-badge: 
    description: Badge from the main branch
    required: false
  github-token:
    description: github token 
    required: true  
  body: 
    description: Theme preview links 
    required: false
      
runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v4.1.1

    - name: Separate redoc links 
      if: ${{ inputs.app-name != '' }}
      shell: bash
      run: | 
        api_links=$(echo "${{ inputs.redoc-links }}" | grep -o '\[${{ inputs.app-name }} - API\]\(([^)]*json)\)'|| echo "-")
        shopify_links=$(echo "${{ inputs.redoc-links }}" | grep -o '\[${{ inputs.app-name }} - Shopify resource models\]\(([^)]*json)\)' || echo "-")
        echo "api_link=$api_links" >> $GITHUB_ENV
        echo "shopify_link=$shopify_links" >> $GITHUB_ENV

    # For BE 
    - name: Run shell script of backend PRs
      if: ${{ inputs.app-name != '' }}
      env:
        BODY: "\n|**App**|**Main branch**|**This PR**|**Redoc link**|**Resource models**|\n|----|---|----|----|----|\n| ${{ inputs.app-name }} | [![Coverage](${{ inputs.main-badge }})](${{ inputs.main-coverage }}) | [![Coverage](${{ inputs.badge }})](${{ inputs.coverage-links }}) | ${{ env.api_link }} | ${{ env.shopify_link }}\n \n"
        GITHUB_TOKEN: ${{ inputs.github-token }} 
      shell: bash
      run: ${{ github.action_path }}/DescriptionUpdate.sh    

    # For FE
    - name: Run shell script for storefront PRs
      if: ${{ inputs.body != '' }}
      env:
        BODY: ${{ inputs.body }}
        GITHUB_TOKEN: ${{ inputs.github-token }} 
      shell: bash
      run: ${{ github.action_path }}/DescriptionUpdate.sh      
